<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'app\\command\\addusercommand' => '/Command/AddUserCommand.php',
                'app\\command\\deleteusercommand' => '/Command/DeleteUserCommand.php',
                'app\\command\\listuserscommand' => '/Command/ListUsersCommand.php',
                'app\\controller\\admin\\blogcontroller' => '/Controller/Admin/BlogController.php',
                'app\\controller\\blogcontroller' => '/Controller/BlogController.php',
                'app\\controller\\securitycontroller' => '/Controller/SecurityController.php',
                'app\\controller\\usercontroller' => '/Controller/UserController.php',
                'app\\datafixtures\\appfixtures' => '/DataFixtures/AppFixtures.php',
                'app\\entity\\comment' => '/Entity/Comment.php',
                'app\\entity\\post' => '/Entity/Post.php',
                'app\\entity\\tag' => '/Entity/Tag.php',
                'app\\entity\\user' => '/Entity/User.php',
                'app\\events' => '/Events.php',
                'app\\eventsubscriber\\checkrequirementssubscriber' => '/EventSubscriber/CheckRequirementsSubscriber.php',
                'app\\eventsubscriber\\commentnotificationsubscriber' => '/EventSubscriber/CommentNotificationSubscriber.php',
                'app\\eventsubscriber\\controllersubscriber' => '/EventSubscriber/ControllerSubscriber.php',
                'app\\eventsubscriber\\redirecttopreferredlocalesubscriber' => '/EventSubscriber/RedirectToPreferredLocaleSubscriber.php',
                'app\\form\\commenttype' => '/Form/CommentType.php',
                'app\\form\\datatransformer\\tagarraytostringtransformer' => '/Form/DataTransformer/TagArrayToStringTransformer.php',
                'app\\form\\posttype' => '/Form/PostType.php',
                'app\\form\\type\\changepasswordtype' => '/Form/Type/ChangePasswordType.php',
                'app\\form\\type\\datetimepickertype' => '/Form/Type/DateTimePickerType.php',
                'app\\form\\type\\tagsinputtype' => '/Form/Type/TagsInputType.php',
                'app\\form\\usertype' => '/Form/UserType.php',
                'app\\kernel' => '/Kernel.php',
                'app\\repository\\postrepository' => '/Repository/PostRepository.php',
                'app\\repository\\tagrepository' => '/Repository/TagRepository.php',
                'app\\repository\\userrepository' => '/Repository/UserRepository.php',
                'app\\security\\postvoter' => '/Security/PostVoter.php',
                'app\\twig\\appextension' => '/Twig/AppExtension.php',
                'app\\twig\\sourcecodeextension' => '/Twig/SourceCodeExtension.php',
                'app\\utils\\markdown' => '/Utils/Markdown.php',
                'app\\utils\\momentformatconverter' => '/Utils/MomentFormatConverter.php',
                'app\\utils\\slugger' => '/Utils/Slugger.php',
                'app\\utils\\validator' => '/Utils/Validator.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
